services:
  web:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
    container_name: fastapi_app
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    command: uv run python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  chromadb:
    image: chromadb/chroma
    container_name: chromadb_server
    volumes:
      - ./data/chroma_db:/data
    ports:
      - "8001:8000"
